"""Deleted 'server_default' settings for 'plan_and_fact' table

Revision ID: 12ca862b26d8
Revises: 6ab893389476
Create Date: 2024-07-04 09:35:29.106930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12ca862b26d8'
down_revision: Union[str, None] = '6ab893389476'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Вручную удалил. Алембик не захотел отображать этот момент
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
