"""Change type column int -> float for 'plan_and_fact' table

Revision ID: 23364b173cca
Revises: ccf5e6d51c6e
Create Date: 2024-07-04 17:48:30.389152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23364b173cca'
down_revision: Union[str, None] = 'ccf5e6d51c6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plan_and_fact', 'plan_average_duration',
               existing_type=sa.SMALLINT(),
               type_=sa.Float(),
               nullable=True)
    op.alter_column('plan_and_fact', 'fact_average_duration',
               existing_type=sa.SMALLINT(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plan_and_fact', 'fact_average_duration',
               existing_type=sa.Float(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    op.alter_column('plan_and_fact', 'plan_average_duration',
               existing_type=sa.Float(),
               type_=sa.SMALLINT(),
               nullable=False)
    # ### end Alembic commands ###
