"""drop column to table 'mailings_2'

Revision ID: 2efd4e043667
Revises: 4d487cd01f30
Create Date: 2024-07-22 12:49:17.140237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2efd4e043667'
down_revision: Union[str, None] = '4d487cd01f30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_event_id', table_name='mailings_2')
    op.alter_column('mailings_2', 'campaign_lead_event_log_id', new_column_name='campaign_event_id')
    op.create_index('ix_sms_campaign_event_id', 'mailings_2', ['campaign_event_id'], unique=False)
    op.drop_column('mailings_2', 'event_id')


        # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('table_name', 'new_column_name', new_column_name='old_column_name')
    op.add_column('mailings_2', sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index('ix_sms_campaign_event_id', table_name='mailings_2')
    op.create_index('ix_event_id', 'mailings_2', ['event_id'], unique=False)
    op.drop_column('mailings_2', 'campaign_event_id')
    # ### end Alembic commands ###
