"""nullable some column 'mailings_2'

Revision ID: 442c3c2e6d2c
Revises: 5fdce3479302
Create Date: 2024-07-24 17:57:55.408509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '442c3c2e6d2c'
down_revision: Union[str, None] = '5fdce3479302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mailings_2', 'campaign_category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mailings_2', 'campaign_category_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('mailings_2', 'campaign_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mailings_2', 'campaign_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('mailings_2', 'campaign_event_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mailings_2', 'source_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('mailings_2', 'source_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mailings_2', 'campaign_event_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mailings_2', 'campaign_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('mailings_2', 'campaign_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mailings_2', 'campaign_category_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('mailings_2', 'campaign_category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
