"""create new table 'mailings_events'

Revision ID: 4e831867481b
Revises: 442c3c2e6d2c
Create Date: 2024-07-29 17:34:22.202789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e831867481b'
down_revision: Union[str, None] = '442c3c2e6d2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailings_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_on_record', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('Europe/Kiev', now())"), nullable=False),
    sa.Column('update_on_record', sa.DateTime(), server_default=sa.text("TIMEZONE('Europe/Kiev', now())"), nullable=False),
    sa.Column('mailing_id', sa.UUID(), nullable=True),
    sa.Column('mailing_category', sa.String(), nullable=True),
    sa.Column('additional_mailing_category', sa.String(), nullable=True),
    sa.Column('event_mailing_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type_offer', sa.String(), nullable=True),
    sa.Column('start_offer_period', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_offer_period', sa.DateTime(timezone=True), nullable=True),
    sa.Column('object_offer_id', sa.Uuid(), nullable=True),
    sa.Column('accepted_offer_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mailing_id'], ['mailings_2.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('mailings_events')
    # ### end Alembic commands ###
