"""create new table 'write_offs'

Revision ID: 697f0c916bc9
Revises: a0b63c1ef0d0
Create Date: 2024-08-01 19:06:32.148995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '697f0c916bc9'
down_revision: Union[str, None] = 'a0b63c1ef0d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('write_offs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_on_record', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('Europe/Kiev', now())"), nullable=False),
    sa.Column('update_on_record', sa.DateTime(), server_default=sa.text("TIMEZONE('Europe/Kiev', now())"), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('identification_number', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Uuid(), nullable=False),
    sa.Column('contract_number', sa.Integer(), nullable=False),
    sa.Column('loan_signed_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('write_off_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('contract_amount', sa.Float(), nullable=False),
    sa.Column('write_off_amount', sa.Float(), nullable=False),
    sa.Column('write_off_reason', sa.String(), nullable=False),
    sa.Column('write_off_comments', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('write_offs_ix_contract_number', 'write_offs', ['contract_number'], unique=False)
    op.create_index('write_offs_ix_identification_number', 'write_offs', ['identification_number'], unique=False)
    op.create_index('write_offs_ix_loan_id', 'write_offs', ['loan_id'], unique=False)
    op.create_index('write_offs_ix_user_id', 'write_offs', ['user_id'], unique=False)
    op.create_index('write_offs_ix_write_off_reason', 'write_offs', ['write_off_reason'], unique=False)
    op.drop_index('ix_date_sent', table_name='mailings_2')
    op.drop_index('ix_id', table_name='mailings_2')
    op.drop_index('ix_lead_id', table_name='mailings_2')
    op.drop_index('ix_mailing_name', table_name='mailings_2')
    op.drop_index('ix_mailing_type', table_name='mailings_2')
    op.drop_index('ix_phone', table_name='mailings_2')
    op.drop_index('ix_sms_campaign_event_id', table_name='mailings_2')
    op.drop_index('ix_sms_id', table_name='mailings_2')
    op.drop_index('ix_sms_stats_id', table_name='mailings_2')
    op.drop_index('ix_sms_version_id', table_name='mailings_2')
    op.drop_index('ix_user_id', table_name='mailings_2')
    op.create_index('mailings2_ix_date_sent', 'mailings_2', ['date_sent'], unique=False)
    op.create_index('mailings2_ix_id', 'mailings_2', ['id'], unique=False)
    op.create_index('mailings2_ix_lead_id', 'mailings_2', ['lead_id'], unique=False)
    op.create_index('mailings2_ix_mailing_name', 'mailings_2', ['mailing_name'], unique=False)
    op.create_index('mailings2_ix_mailing_type', 'mailings_2', ['mailing_type'], unique=False)
    op.create_index('mailings2_ix_phone', 'mailings_2', ['phone'], unique=False)
    op.create_index('mailings2_ix_sms_campaign_event_id', 'mailings_2', ['campaign_event_id'], unique=False)
    op.create_index('mailings2_ix_sms_id', 'mailings_2', ['sms_id'], unique=False)
    op.create_index('mailings2_ix_sms_stats_id', 'mailings_2', ['sms_stats_id'], unique=True)
    op.create_index('mailings2_ix_sms_version_id', 'mailings_2', ['sms_version_id'], unique=False)
    op.create_index('mailings2_ix_user_id', 'mailings_2', ['user_id'], unique=False)
    op.drop_index('ix_object_mailing_group_id', table_name='mailings_events')
    op.create_index('mailings_events_ix_mailing_id', 'mailings_events', ['mailing_id'], unique=False)
    op.create_index('mailings_events_ix_object_mailing_group_id', 'mailings_events', ['mailing_group_id'], unique=False)
    op.create_index('mailings_events_ix_object_offer_id', 'mailings_events', ['object_offer_id'], unique=False)
    op.create_index('plan_and_fact_pkey', 'plan_and_fact', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('plan_and_fact_pkey', table_name='plan_and_fact')
    op.drop_index('mailings_events_ix_object_offer_id', table_name='mailings_events')
    op.drop_index('mailings_events_ix_object_mailing_group_id', table_name='mailings_events')
    op.drop_index('mailings_events_ix_mailing_id', table_name='mailings_events')
    op.create_index('ix_object_mailing_group_id', 'mailings_events', ['mailing_group_id'], unique=False)
    op.drop_index('mailings2_ix_user_id', table_name='mailings_2')
    op.drop_index('mailings2_ix_sms_version_id', table_name='mailings_2')
    op.drop_index('mailings2_ix_sms_stats_id', table_name='mailings_2')
    op.drop_index('mailings2_ix_sms_id', table_name='mailings_2')
    op.drop_index('mailings2_ix_sms_campaign_event_id', table_name='mailings_2')
    op.drop_index('mailings2_ix_phone', table_name='mailings_2')
    op.drop_index('mailings2_ix_mailing_type', table_name='mailings_2')
    op.drop_index('mailings2_ix_mailing_name', table_name='mailings_2')
    op.drop_index('mailings2_ix_lead_id', table_name='mailings_2')
    op.drop_index('mailings2_ix_id', table_name='mailings_2')
    op.drop_index('mailings2_ix_date_sent', table_name='mailings_2')
    op.create_index('ix_user_id', 'mailings_2', ['user_id'], unique=False)
    op.create_index('ix_sms_version_id', 'mailings_2', ['sms_version_id'], unique=False)
    op.create_index('ix_sms_stats_id', 'mailings_2', ['sms_stats_id'], unique=True)
    op.create_index('ix_sms_id', 'mailings_2', ['sms_id'], unique=False)
    op.create_index('ix_sms_campaign_event_id', 'mailings_2', ['campaign_event_id'], unique=False)
    op.create_index('ix_phone', 'mailings_2', ['phone'], unique=False)
    op.create_index('ix_mailing_type', 'mailings_2', ['mailing_type'], unique=False)
    op.create_index('ix_mailing_name', 'mailings_2', ['mailing_name'], unique=False)
    op.create_index('ix_lead_id', 'mailings_2', ['lead_id'], unique=False)
    op.create_index('ix_id', 'mailings_2', ['id'], unique=True)
    op.create_index('ix_date_sent', 'mailings_2', ['date_sent'], unique=False)
    op.drop_index('write_offs_ix_write_off_reason', table_name='write_offs')
    op.drop_index('write_offs_ix_user_id', table_name='write_offs')
    op.drop_index('write_offs_ix_loan_id', table_name='write_offs')
    op.drop_index('write_offs_ix_identification_number', table_name='write_offs')
    op.drop_index('write_offs_ix_contract_number', table_name='write_offs')
    op.drop_table('write_offs')
    # ### end Alembic commands ###
