"""Add index for 'plan_and_fact' table

Revision ID: 6ab893389476
Revises: e4332761c305
Create Date: 2024-07-03 17:51:34.493031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ab893389476'
down_revision: Union[str, None] = 'e4332761c305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_created_on', 'plan_and_fact', ['created_on'], unique=False)
    op.create_index('ix_created_on_&_report_type_&_product_type', 'plan_and_fact', ['created_on', 'report_type', 'product_type'], unique=False)
    op.create_index('ix_id', 'plan_and_fact', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_id', table_name='plan_and_fact')
    op.drop_index('ix_created_on_&_report_type_&_product_type', table_name='plan_and_fact')
    op.drop_index('ix_created_on', table_name='plan_and_fact')
    # ### end Alembic commands ###
