"""add offer period column to 'mailings_2'

Revision ID: 6f6f7fce6fd3
Revises: c6305c39a245
Create Date: 2024-07-23 11:53:38.161435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f6f7fce6fd3'
down_revision: Union[str, None] = 'c6305c39a245'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailings_2', sa.Column('start_offer_period', sa.DATE(), nullable=True))
    op.add_column('mailings_2', sa.Column('end_offer_period', sa.DATE(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mailings_2', 'end_offer_period')
    op.drop_column('mailings_2', 'start_offer_period')
    # ### end Alembic commands ###
