"""Float -> Numeric to 'plan_and_fact' table

Revision ID: 962111077d92
Revises: bd26a78964b2
Create Date: 2024-07-07 10:20:40.945683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '962111077d92'
down_revision: Union[str, None] = 'bd26a78964b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plan_and_fact', 'plan_sum',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('plan_and_fact', 'plan_average_duration',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('plan_and_fact', 'fact_sum',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('plan_and_fact', 'fact_average_duration',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plan_and_fact', 'fact_average_duration',
               existing_type=sa.Numeric(precision=8, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('plan_and_fact', 'fact_sum',
               existing_type=sa.Numeric(precision=8, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('plan_and_fact', 'plan_average_duration',
               existing_type=sa.Numeric(precision=8, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('plan_and_fact', 'plan_sum',
               existing_type=sa.Numeric(precision=8, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    # ### end Alembic commands ###
