"""change type promo column (null true) 'mailings_2'

Revision ID: a02df0705e8b
Revises: 6f6f7fce6fd3
Create Date: 2024-07-23 15:52:29.416960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a02df0705e8b'
down_revision: Union[str, None] = '6f6f7fce6fd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mailings_2', 'promo_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('mailings_2', 'promo_code_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('mailings_2', 'promo_code_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('mailings_2', 'promo_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
