"""add new column 'mailing_group_id'  to 'mailings_events'

Revision ID: a0b63c1ef0d0
Revises: 4e831867481b
Create Date: 2024-08-01 12:32:34.959945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0b63c1ef0d0'
down_revision: Union[str, None] = '4e831867481b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('mailings_events', sa.Column('mailing_group_id', sa.Uuid(), nullable=True))
    op.create_index('ix_object_mailing_group_id', 'mailings_events', ['mailing_group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_object_mailing_group_id', table_name='mailings_events')
    op.drop_column('mailings_events', 'mailing_group_id')
    # ### end Alembic commands ###
