"""Set default value in column for 'plan_and_fact' table

Revision ID: ccf5e6d51c6e
Revises: 3dbf4aa6b92a
Create Date: 2024-07-04 13:57:32.994278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccf5e6d51c6e'
down_revision: Union[str, None] = '3dbf4aa6b92a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Вручную Добавил. Алембик не захотел отображать этот момент
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
