"""change type column to 'write_offs'

Revision ID: d020d171a9da
Revises: 697f0c916bc9
Create Date: 2024-08-01 19:22:56.296817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd020d171a9da'
down_revision: Union[str, None] = '697f0c916bc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('write_offs', 'write_off_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('write_offs', 'write_off_date',
               existing_type=sa.DATE(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###
